image: node:20

stages:
  - test
  - build

cache:
  paths:
    - node_modules/
    - tc/node_modules/
    - tests/node_modules/

before_script:
  - npm install -g typescript vitest

test:
  stage: test
  script:
    - cd tc
    - tsc lab5.ts
    - node lab5.js
    - cd ../tests
    - npm install
    - npm test
  only:
    - lab6

build:
  stage: build
  script:
    - make
  only:
    - lab6