image: node:20

stages:
  - install
  - test
  - build

cache:
  paths:
    - tc/node_modules/

before_script:
  - cd tc
  - npm install

install:
  stage: install
  script:
    - echo "Dependencies installed"
  only:
    - lab7

test:
  stage: test
  script:
    - npm test -- --run
  only:
    - lab7

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - tc/dist/
    expire_in: 1 week
  only:
    - lab7