image: node:18

stages:
  - test

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install -g typescript       
    - cd tc
    - tsc lab3.ts                    
    - node lab3.js
    - cd ../tests
    - npm install
    - npm test
  only:
    - branches